version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: MR
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - my_network

  db_init:
    build:
      context: ./db_init
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: examplepassword
    networks:
      - my_network

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - "5500:5000"
    networks:
      - my_network

  records:
    build:
      context: ./records
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - "5001:5001"
    networks:
      - my_network


  questions:
    build:
      context: ./questions
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - "5002:5002"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
